format = """
$sudo\
$username\
$directory\
$git_branch\
$git_status\
[ ](fg:#FF0000)\
$fill\
$shell\
$conda\
$python\
$nodejs\
$c\
$rust\
$line_break\
$memory_usage\
$character
"""

# [ ](fg:#FF0000)

[character]
success_symbol = "[](bold white)"
error_symbol = "[](bold red)"

[username]
show_always = true
style_user = "fg:#8BE9FD bold"
style_root = "fg:# bold"
format = "[$user ]($style)"
disabled = false

[directory]
style = "fg:#F1FA8C"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[conda]
symbol = " "
style = "fg:#77DD77"
format = "[$symbol$environment ]($style)"
ignore_base = false

[python]
symbol = " "
style = "fg:#3776AB"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[c]
symbol = " "
format = "[$symbol($version )]($style)"

[git_branch]
symbol = " "
style = "fg:#FFA500 bold"
format = "[$symbol$branch ]($style)"

[git_status]
style = "fg:#FFC0CB"
format = "[$all_status$ahead_behind ]($style)"

[fill]
symbol = " "

[shell]
disabled = false

[localip]
ssh_only = false
disabled = false
style = "fg:#40E0D0 bold"

[memory_usage]
disabled = false
threshold = 75
symbol = " "
format = "[$symbol${ram} ]($style)"

[nodejs]
format = "[$symbol($version) ]($style)"

[rust]
format = "[$symbol($version )]($style)"

[sudo]
symbol = " "
style = "fg:#8BE9FD bold"
format = "[$symbol]($style)"
disabled = false
